version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vgc_website
      POSTGRES_USER: vgc_user
      POSTGRES_PASSWORD: vgc_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vgc_user -d vgc_website"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
