version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vgc_website
      POSTGRES_USER: vgc_user
      POSTGRES_PASSWORD: vgc_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vgc_user -d vgc_website"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings.dev
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=vgc_website
      - DB_USER=vgc_user
      - DB_PASSWORD=vgc_password
      - SECRET_KEY=django-insecure-development-key-change-in-production
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media

volumes:
  postgres_data:
  static_volume:
  media_volume:
